name: KinoLondon
favicon: null
layout_spectrum: 0.9430484143085778
typography_spectrum: 0.6266091645229608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10681571019813418
  lightness: 0.31434760708361864
  saturation: 0.342032095650211
  rhythmicContrast: 0.46521610324271023
purpose: []
